---
- name: Create configuration directory /etc/fail2ban
  file:
    state: directory
    path: /etc/fail2ban

- name: Create jail.local config
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify: Reload fail2ban

- name: Install fail2ban
  apt:
    name: fail2ban

- name: Start and enable fail2ban service
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: Copy filters
  copy:
    src: filter.d/
    dest: /etc/fail2ban/filter.d/
    mode: 0644
    owner: root
    group: root
  notify: Reload fail2ban

- name: Copy actions
  copy:
    src: action.d/
    dest: /etc/fail2ban/action.d/
    mode: 0644
    owner: root
    group: root
  notify: Reload fail2ban
