---
- name: Make folder /etc/fail2ban
  file:
    state: directory
    path: /etc/fail2ban

- name: Create jail.local config
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify: Restart fail2ban

- name: Install fail2ban
  apt:
    name: fail2ban

- name: Start fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes
